### ISSUE TITLE
How to generate training and testing data of senz3d_data ?

### ISSUE THREAD

**Issue by cuge1995** [sbhonde1/Multimodal-Learning#2]

**Comment by sbhonde1** [comment]
For now, You have to keep it in seperate folders. I will give an update for random train-val split.

**Comment by cuge1995** [comment]
> For now, You have to keep it in seperate folders. I will give an update for random train-val split.

thanks

**Comment by cuge1995** [comment]
> For now, You have to keep it in seperate folders. I will give an update for random train-val split.

Could you update it as soon as possible

**Comment by badri2304** [comment]
@sbhonde1 Any update on the split ?
